<a href="https://colab.research.google.com/github/julmiha25-sys/Python/blob/main/%D0%A1%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B0_%D1%82%D0%B0%D0%BA%D1%81%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

c=([1,2,3],[4,5,6])
a=np.array(c)
a[1:,0:2]
a[::-1]
c=np.array([1,2,3,4,5,6])
c[1:]


array([2, 3, 4, 5, 6])

In [ ]:
class Answer:
    def ArrayIndexing(self, arr, rows, val):
        if arr.shape[0]>=(val+1):
          res=arr[:(rows[1]+1),::val+1]
        else:
          res=arr[:(rows[0]),:1]
        return res

arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
rows = [0, 1]
val = 2
c=Answer()
print(c.ArrayIndexing(arr, rows, val))


[[1 4]
 [1 4]]


In [ ]:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
arr.shape
arr.shape[0]

3

In [ ]:
import numpy as np
def solve_linear_equations(A, b):
  res=np.linalg.solve(A,b)
  return res



 # Допустим есть следующая СЛУ
#2x + 3y + z = 10
# x +  y + z =  6
#3x + 2y + 2z = 12

# Матрица коэффициентов будет выглядеть следующим образом:
A = np.array([[2, 3, 1],
              [1, 1, 1],
              [3, 2, 2]])

# Вектор правой части:
b = np.array([10, 6, 12])

solve_linear_equations(A, b)
# [2.96059473e-16 2.00000000e+00 4.00000000e+00]

array([1.48029737e-16, 2.00000000e+00, 4.00000000e+00])

In [12]:
import numpy as np
float_formatter="{:.2f}".format
np.set_printoptions(formatter={"float_kind":float_formatter})
data=np.genfromtxt('data.csv',delimiter=',',skip_header=True)
spid_arr=data[:,7]/(data[:,8]/3600) # Массив со скоростями поездок (расстояние/время)
spid_arr.mean() # Средняя скорость такси
data[data[:,1]==2] # Выбор статистики поездок за февраль
np.shape(data[data[:,1]==2])[0] # Кол-в поездок за февраль
data[data[:,12]>50] # Выбор статистики поездок с чаевыми более 50$
np.shape(data[data[:,12]>50])[0] # Кол-в поездок с чаевыми более 50$
np.cov(data[:,[7,8,-2,-3]],rowvar=False) # Массив ковариаций - как связаны длительность по времени, по расстоянию, стоимость поездки и чаевые


array([[26.71, 3413.20, 68.19, 6.67],
       [3413.20, 10489667.24, 11345.40, 924.20],
       [68.19, 11345.40, 269.92, 45.80],
       [6.67, 924.20, 45.80, 23.35]])